# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: githat 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "githat"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Bernardo B. Marques"]
  s.date = "2014-01-17"
  s.description = "git diff with code syntax highlight"
  s.email = "bernardo.fire@gmail.com"
  s.executables = ["git-hat"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.mkd"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.mkd",
    "Rakefile",
    "VERSION",
    "bin/git-hat",
    "githat.gemspec",
    "githat.png",
    "lib/githat.rb",
    "lib/pagination.rb",
    "spec/githat_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/bernardofire/githat"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.1"
  s.summary = nil

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bundler>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<pygments.rb>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<pygments.rb>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<pygments.rb>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

